language: rust
cache: cargo

rust:
  - beta # Rust 1.25
  - nightly

matrix:
  include:
    # 64-bit macOS
    - rust: beta # Rust 1.25
      os: osx
    # Clippy lints
    - rust: nightly
      env: CLIPPY="true"
      install:
        - cargo install clippy --debug --force
      script:
        - cargo clippy -- -Dclippy

script:
  - cargo test
