environment:
  matrix:
    # Beta channel
    - TARGET:  "x86_64-pc-windows-gnu"
      CHANNEL: "beta"
    - TARGET:  "x86_64-pc-windows-msvc"
      CHANNEL: "beta"
    # Nightly channel
    - TARGET:  "x86_64-pc-windows-gnu"
      CHANNEL: "nightly"
    - TARGET:  "x86_64-pc-windows-msvc"
      CHANNEL: "nightly"

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

# `cargo test` takes care of this
build: false

test_script:
  - cargo test
